### ISSUE TITLE
How to create an event ?

### ISSUE THREAD

**Issue by l0tusbiswas** [Maxim-Mazurok/angular-google-calendar-typescript-example#5]
Hey, can you please let me know, how to create an event in google calendar, once we authenticate a user ?

**Comment by Maxim-Mazurok** [comment]
Hello! Please, refer to the official documentation: https://developers.google.com/calendar/api/guides/create-events#javascript

This project is a demo of how to use client-side/browser (JS, not NodeJS) Google Calendar API with TypeScript and type definitions generated and published by https://github.com/Maxim-Mazurok/google-api-typings-generator

Feel free to reopen or create another issue if you have questions related to these projects, thanks :)
