### ISSUE TITLE
Does not work with angular 15

### ISSUE THREAD

**Issue by rajesh99** [Maxim-Mazurok/angular-google-calendar-typescript-example#6]
It does not work with angular. It say deprecated.

**Comment by Maxim-Mazurok** [comment]
I think this example was created for Angular 9.
The goal was to demonstrate the correct usage of `@types/gapi.client.calendar` package.
I will not be updating it to Angular 15 for now as it's outside of the scope of the project, cheers!

**Comment by rajesh99** [comment]
It is better to update to angular 15 and show. Similar upgrades could be followed by the community for future angular upgrades.  Currently this is unusable for angular 15.

Otherwise, can you point to any github projects using upgraded package.  Thanks.

**Comment by Maxim-Mazurok** [comment]
To clarify the idea of the project is not to show how to use google calendar with Angular, but how to use typescript type definitions for the Google calendar API.

Me and this project are not affiliated with Google in any way.

I'm not aware of any other similar projects. My general thought would be that there shouldn't be much of a difference in Google calendar API usage.l between different frameworks, so you might be able to apply the same technique to any framework/version. Hope this helps, please open a new issue if you have trouble running this project as outlined in readme, cheers!
